package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/wilddogjp/bpx/pkg/uasset"
)

const (
	blueprintsObjectVersionGUID  = "b0d832e4-1f89-4f0d-accf-7eb736fd4aa2"
	frameworkObjectVersionGUID   = "cffc743f-43b0-4480-9391-14df171d2073"
	ue5MainObjectVersionGUID     = "697dd581-e64f-41ab-aa4a-51ecbeb7b628"
	ue5ReleaseObjectVersionGUID  = "d89b5e42-24bd-4d46-8412-aca8df641779"
	releaseObjectVersionGUID     = "9c54d522-a826-4fbe-9421-074661b482d0"
	blueprintVerEdGraphOptimized = int32(4)
	frameworkVerPinContainerType = int32(26)
	frameworkVerPinsStoreFName   = int32(31)
	releaseVerPinUObjectWrapper  = int32(32)
	ue5MainVerPinSourceIndex     = int32(50)
	ue5ReleaseVerPinFloatSingle  = int32(36)
	maxBlueprintGraphPins        = int32(4096)
	maxBlueprintPinRefs          = int32(8192)
)

type blueprintGraphParseConfig struct {
	PinsStoreFName                 bool
	HasPinFriendlyName             bool
	HasSourceIndex                 bool
	HasPinContainerType            bool
	HasPinUObjectWrapper           bool
	HasPinSerializeAsSinglePrecise bool
}

type blueprintPinReference struct {
	OwningNodeIndex int32
	PinGUID         string
}

type blueprintResolvedPinLink struct {
	ExportIndex   int
	NodeName      string
	NodeClassName string
	PinName       string
	PinDirection  int
	PinCategory   string
}

type blueprintNodePin struct {
	Index                    int
	Name                     string
	Direction                int
	DirectionName            string
	Category                 string
	SubCategory              string
	ContainerType            string
	DefaultValue             string
	AutogeneratedDefault     string
	DefaultTextValue         string
	DefaultObjectIndex       int32
	DefaultObjectResolved    string
	PinGUID                  string
	OwningNodeIndex          int32
	SourceIndex              int32
	PersistentGUID           string
	PersistentFlags          uint32
	LinkedToRefs             []blueprintPinReference
	SubPinsRefs              []blueprintPinReference
	ParentPinRef             *blueprintPinReference
	ReferencePassThroughRef  *blueprintPinReference
	LinkedTo                 []blueprintResolvedPinLink
	UnresolvedLinkedTo       []blueprintPinReference
	ParseWarnings            []string
	PinFriendlyName          string
	PinToolTip               string
	SubCategoryObjectIndex   int32
	SubCategoryObjectResolve string
}

type blueprintGraphNode struct {
	ExportIndex           int
	ObjectName            string
	ClassName             string
	OuterIndex            int32
	GraphPath             []string
	GraphName             string
	NodePosX              int
	NodePosY              int
	NodePosFound          bool
	NodeGUID              string
	FunctionMemberName    string
	FunctionMemberParent  string
	EventMemberName       string
	EventMemberParent     string
	CustomFunctionName    string
	EventSignatureName    string
	DelegatePropertyName  string
	PropertiesWarnings    []string
	PinParseWarnings      []string
	Pins                  []blueprintNodePin
	PinParseStartOffset   int
	PinParseConsumedBytes int
	pinParseConfig        blueprintGraphParseConfig
	decodedProperties     map[string]any
}

type blueprintExecutionEdge struct {
	FromExportIndex int
	FromNodeName    string
	FromPin         string
	ToExportIndex   int
	ToNodeName      string
	ToPin           string
}

type blueprintGraphIndex struct {
	Nodes        []blueprintGraphNode
	Edges        []blueprintExecutionEdge
	Warnings     []string
	nodeByExport map[int]int
}

type blueprintNodePinsParseResult struct {
	Pins       []blueprintNodePin
	Start      int
	Consumed   int
	Remaining  int
	Warnings   []string
	ConfigUsed blueprintGraphParseConfig
}

func runBlueprintTrace(args []string, stdout, stderr io.Writer) int {
	fs := newFlagSet("blueprint trace", stderr)
	opts := registerCommonFlags(fs)
	from := fs.String("from", "", "start node token: NodeName or NodeName.PinName")
	toNode := fs.String("to-node", "", "target node token")
	toFunction := fs.String("to-function", "", "target member token (e.g. OpenLevelBySoftObjectPtr)")
	maxDepth := fs.Int("max-depth", 128, "maximum traversal depth")
	if err := parseFlagSet(fs, args); err != nil {
		return 1
	}
	if fs.NArg() != 1 || strings.TrimSpace(*from) == "" || (strings.TrimSpace(*toNode) == "" && strings.TrimSpace(*toFunction) == "") {
		fmt.Fprintln(stderr, "usage: bpx blueprint trace <file.uasset> --from <Node|Node.Pin> [--to-node <token>] [--to-function <token>] [--max-depth <n>]")
		return 1
	}
	file := fs.Arg(0)
	asset, err := uasset.ParseFile(file, *opts)
	if err != nil {
		fmt.Fprintf(stderr, "error: %v\n", err)
		return 1
	}
	graph := buildBlueprintGraphIndex(asset)

	fromNodeToken, fromPinToken := splitNodePinToken(*from)
	startExports := findBlueprintNodeExports(graph, fromNodeToken)
	if len(startExports) == 0 {
		fmt.Fprintf(stderr, "error: no node matched --from token %q\n", fromNodeToken)
		return 1
	}
	if *maxDepth <= 0 {
		fmt.Fprintln(stderr, "error: --max-depth must be > 0")
		return 1
	}

	targetNodeToken := strings.TrimSpace(*toNode)
	targetFunctionToken := strings.TrimSpace(*toFunction)
	targetFn := func(n blueprintGraphNode) bool {
		if targetNodeToken != "" && !nodeMatchesToken(n, targetNodeToken) {
			return false
		}
		if targetFunctionToken != "" && !nodeMatchesMember(n, targetFunctionToken) {
			return false
		}
		return true
	}

	path, targetExport, found := traceBlueprintExecutionPath(graph, startExports, fromPinToken, targetFn, *maxDepth)
	pathItems := make([]map[string]any, 0, len(path))
	for i, edge := range path {
		pathItems = append(pathItems, map[string]any{
			"step":       i + 1,
			"fromExport": edge.FromExportIndex,
			"fromNode":   edge.FromNodeName,
			"fromPin":    edge.FromPin,
			"toExport":   edge.ToExportIndex,
			"toNode":     edge.ToNodeName,
			"toPin":      edge.ToPin,
		})
	}

	startNodes := make([]map[string]any, 0, len(startExports))
	for _, exportIndex := range startExports {
		node := graph.nodeForExport(exportIndex)
		if node == nil {
			continue
		}
		startNodes = append(startNodes, map[string]any{
			"export":     node.ExportIndex,
			"objectName": node.ObjectName,
			"className":  node.ClassName,
			"graphName":  node.GraphName,
		})
	}

	resp := map[string]any{
		"file":         file,
		"from":         *from,
		"toNode":       targetNodeToken,
		"toFunction":   targetFunctionToken,
		"maxDepth":     *maxDepth,
		"nodeCount":    len(graph.Nodes),
		"edgeCount":    len(graph.Edges),
		"startNodes":   startNodes,
		"found":        found,
		"pathLength":   len(pathItems),
		"path":         pathItems,
		"graphWarning": graph.Warnings,
	}
	if found {
		if node := graph.nodeForExport(targetExport); node != nil {
			resp["target"] = map[string]any{
				"export":             node.ExportIndex,
				"objectName":         node.ObjectName,
				"className":          node.ClassName,
				"graphName":          node.GraphName,
				"functionMemberName": node.FunctionMemberName,
				"eventMemberName":    node.EventMemberName,
				"customFunctionName": node.CustomFunctionName,
			}
		}
	}
	return printJSON(stdout, resp)
}

func runBlueprintCallArgs(args []string, stdout, stderr io.Writer) int {
	fs := newFlagSet("blueprint call-args", stderr)
	opts := registerCommonFlags(fs)
	member := fs.String("member", "", "function/member token")
	classFilter := fs.String("class", "K2Node_CallFunction", "class token filter")
	allPins := fs.Bool("all-pins", false, "include non-input pins")
	includeExec := fs.Bool("include-exec", false, "include exec pins")
	if err := parseFlagSet(fs, args); err != nil {
		return 1
	}
	if fs.NArg() != 1 || strings.TrimSpace(*member) == "" {
		fmt.Fprintln(stderr, "usage: bpx blueprint call-args <file.uasset> --member <token> [--class <token>] [--all-pins] [--include-exec]")
		return 1
	}

	file := fs.Arg(0)
	asset, err := uasset.ParseFile(file, *opts)
	if err != nil {
		fmt.Fprintf(stderr, "error: %v\n", err)
		return 1
	}
	graph := buildBlueprintGraphIndex(asset)

	memberToken := strings.TrimSpace(*member)
	classToken := strings.TrimSpace(*classFilter)
	matches := make([]map[string]any, 0, 16)
	for _, node := range graph.Nodes {
		if classToken != "" && !containsFold(node.ClassName, classToken) {
			continue
		}
		if !nodeMatchesMember(node, memberToken) {
			continue
		}
		pins := make([]map[string]any, 0, len(node.Pins))
		for _, pin := range node.Pins {
			if !*includeExec && isBlueprintExecPin(pin) {
				continue
			}
			if !*allPins && pin.Direction != 0 {
				continue
			}
			defaultValue, defaultSource := summarizeBlueprintPinDefault(pin)
			links := make([]string, 0, len(pin.LinkedTo))
			for _, link := range pin.LinkedTo {
				links = append(links, fmt.Sprintf("%s.%s", link.NodeName, link.PinName))
			}
			sort.Strings(links)
			pins = append(pins, map[string]any{
				"pin":           pin.Name,
				"direction":     pin.DirectionName,
				"category":      pin.Category,
				"default":       defaultValue,
				"defaultSource": defaultSource,
				"linkedCount":   len(links),
				"linkedTo":      links,
			})
		}
		matches = append(matches, map[string]any{
			"export":             node.ExportIndex,
			"objectName":         node.ObjectName,
			"className":          node.ClassName,
			"graphName":          node.GraphName,
			"functionMemberName": node.FunctionMemberName,
			"eventMemberName":    node.EventMemberName,
			"customFunctionName": node.CustomFunctionName,
			"pins":               pins,
		})
	}
	sort.Slice(matches, func(i, j int) bool {
		return asIntFromAny(matches[i]["export"]) < asIntFromAny(matches[j]["export"])
	})

	return printJSON(stdout, map[string]any{
		"file":        file,
		"member":      memberToken,
		"classFilter": classToken,
		"allPins":     *allPins,
		"includeExec": *includeExec,
		"matchCount":  len(matches),
		"matches":     matches,
		"warnings":    graph.Warnings,
	})
}

func runBlueprintRefs(args []string, stdout, stderr io.Writer) int {
	fs := newFlagSet("blueprint refs", stderr)
	opts := registerCommonFlags(fs)
	softPath := fs.String("soft-path", "", "soft object path token")
	classFilter := fs.String("class", "", "optional class token filter")
	includeRoutes := fs.Bool("include-routes", true, "include event->node routes")
	maxRoutes := fs.Int("max-routes", 3, "maximum route count per match")
	maxDepth := fs.Int("max-depth", 128, "maximum route depth")
	if err := parseFlagSet(fs, args); err != nil {
		return 1
	}
	if fs.NArg() != 1 || strings.TrimSpace(*softPath) == "" {
		fmt.Fprintln(stderr, "usage: bpx blueprint refs <file.uasset> --soft-path <path> [--class <token>] [--include-routes] [--max-routes <n>] [--max-depth <n>]")
		return 1
	}
	if *maxRoutes < 0 {
		fmt.Fprintln(stderr, "error: --max-routes must be >= 0")
		return 1
	}
	if *maxDepth <= 0 {
		fmt.Fprintln(stderr, "error: --max-depth must be > 0")
		return 1
	}

	file := fs.Arg(0)
	asset, err := uasset.ParseFile(file, *opts)
	if err != nil {
		fmt.Fprintf(stderr, "error: %v\n", err)
		return 1
	}
	graph := buildBlueprintGraphIndex(asset)
	softPathToken := strings.TrimSpace(*softPath)

	eventExports := collectBlueprintEventExports(graph)
	classToken := strings.TrimSpace(*classFilter)
	matches := make([]map[string]any, 0, 16)

	for _, node := range graph.Nodes {
		if classToken != "" && !containsFold(node.ClassName, classToken) {
			continue
		}
		for _, pin := range node.Pins {
			hitValue, source, ok := matchBlueprintSoftPathOnPin(pin, softPathToken)
			if !ok {
				continue
			}
			links := make([]string, 0, len(pin.LinkedTo))
			for _, link := range pin.LinkedTo {
				links = append(links, fmt.Sprintf("%s.%s", link.NodeName, link.PinName))
			}
			sort.Strings(links)

			routes := make([]map[string]any, 0)
			if *includeRoutes && *maxRoutes != 0 {
				for _, eventExport := range eventExports {
					if eventExport == node.ExportIndex {
						continue
					}
					path, _, found := traceBlueprintExecutionPath(graph, []int{eventExport}, "", func(n blueprintGraphNode) bool {
						return n.ExportIndex == node.ExportIndex
					}, *maxDepth)
					if !found {
						continue
					}
					eventNode := graph.nodeForExport(eventExport)
					pathItems := make([]map[string]any, 0, len(path))
					for i, edge := range path {
						pathItems = append(pathItems, map[string]any{
							"step":       i + 1,
							"fromExport": edge.FromExportIndex,
							"fromNode":   edge.FromNodeName,
							"fromPin":    edge.FromPin,
							"toExport":   edge.ToExportIndex,
							"toNode":     edge.ToNodeName,
							"toPin":      edge.ToPin,
						})
					}
					routes = append(routes, map[string]any{
						"eventExport":   eventExport,
						"eventNode":     eventNode.ObjectName,
						"eventMember":   firstNonEmpty(eventNode.EventMemberName, eventNode.CustomFunctionName),
						"pathLength":    len(pathItems),
						"executionPath": pathItems,
					})
					if *maxRoutes > 0 && len(routes) >= *maxRoutes {
						break
					}
				}
			}

			matches = append(matches, map[string]any{
				"export":      node.ExportIndex,
				"objectName":  node.ObjectName,
				"className":   node.ClassName,
				"graphName":   node.GraphName,
				"pin":         pin.Name,
				"direction":   pin.DirectionName,
				"value":       hitValue,
				"valueSource": source,
				"linkedTo":    links,
				"eventRoutes": routes,
			})
		}
	}
	return printJSON(stdout, map[string]any{
		"file":               file,
		"softPath":           softPathToken,
		"classFilter":        classToken,
		"includeRoutes":      *includeRoutes,
		"maxRoutes":          *maxRoutes,
		"maxDepth":           *maxDepth,
		"eventNodeCount":     len(eventExports),
		"matchCount":         len(matches),
		"matches":            matches,
		"graphParseWarnings": graph.Warnings,
	})
}

func runBlueprintSearch(args []string, stdout, stderr io.Writer) int {
	fs := newFlagSet("blueprint search", stderr)
	opts := registerCommonFlags(fs)
	classFilter := fs.String("class", "", "optional class token")
	memberFilter := fs.String("member", "", "optional member token")
	nameFilter := fs.String("name", "", "optional node object name token")
	show := fs.String("show", "NodePos,Function,PinDefaults", "comma-separated fields: NodePos,Function,PinDefaults,Pins,Warnings")
	limit := fs.Int("limit", 0, "optional result limit (0 = unlimited)")
	if err := parseFlagSet(fs, args); err != nil {
		return 1
	}
	if fs.NArg() != 1 {
		fmt.Fprintln(stderr, "usage: bpx blueprint search <file.uasset> [--class <token>] [--member <token>] [--name <token>] [--show <fields>] [--limit <n>]")
		return 1
	}
	if *limit < 0 {
		fmt.Fprintln(stderr, "error: --limit must be >= 0")
		return 1
	}

	showFields, err := parseBlueprintShowFields(*show)
	if err != nil {
		fmt.Fprintf(stderr, "error: %v\n", err)
		return 1
	}

	file := fs.Arg(0)
	asset, err := uasset.ParseFile(file, *opts)
	if err != nil {
		fmt.Fprintf(stderr, "error: %v\n", err)
		return 1
	}
	graph := buildBlueprintGraphIndex(asset)

	classToken := strings.TrimSpace(*classFilter)
	memberToken := strings.TrimSpace(*memberFilter)
	nameToken := strings.TrimSpace(*nameFilter)

	matches := make([]map[string]any, 0, 32)
	for _, node := range graph.Nodes {
		if classToken != "" && !containsFold(node.ClassName, classToken) {
			continue
		}
		if memberToken != "" && !nodeMatchesMember(node, memberToken) {
			continue
		}
		if nameToken != "" && !containsFold(node.ObjectName, nameToken) {
			continue
		}

		item := map[string]any{
			"export":     node.ExportIndex,
			"objectName": node.ObjectName,
			"className":  node.ClassName,
			"graphName":  node.GraphName,
			"nodeGuid":   node.NodeGUID,
		}
		for _, field := range showFields {
			switch field {
			case "NodePos":
				if node.NodePosFound {
					item["nodePos"] = map[string]any{"x": node.NodePosX, "y": node.NodePosY}
				}
			case "Function":
				item["function"] = map[string]any{
					"functionMemberName":   node.FunctionMemberName,
					"functionMemberParent": node.FunctionMemberParent,
					"eventMemberName":      node.EventMemberName,
					"eventMemberParent":    node.EventMemberParent,
					"customFunctionName":   node.CustomFunctionName,
					"eventSignatureName":   node.EventSignatureName,
					"delegatePropertyName": node.DelegatePropertyName,
				}
			case "PinDefaults":
				pinDefaults := make([]map[string]any, 0, len(node.Pins))
				for _, pin := range node.Pins {
					if isBlueprintExecPin(pin) {
						continue
					}
					defaultValue, source := summarizeBlueprintPinDefault(pin)
					links := make([]string, 0, len(pin.LinkedTo))
					for _, link := range pin.LinkedTo {
						links = append(links, fmt.Sprintf("%s.%s", link.NodeName, link.PinName))
					}
					sort.Strings(links)
					pinDefaults = append(pinDefaults, map[string]any{
						"pin":           pin.Name,
						"direction":     pin.DirectionName,
						"category":      pin.Category,
						"default":       defaultValue,
						"defaultSource": source,
						"linkedTo":      links,
					})
				}
				item["pinDefaults"] = pinDefaults
			case "Pins":
				pins := make([]map[string]any, 0, len(node.Pins))
				for _, pin := range node.Pins {
					links := make([]string, 0, len(pin.LinkedTo))
					for _, link := range pin.LinkedTo {
						links = append(links, fmt.Sprintf("%s.%s", link.NodeName, link.PinName))
					}
					sort.Strings(links)
					pins = append(pins, map[string]any{
						"pin":         pin.Name,
						"direction":   pin.DirectionName,
						"category":    pin.Category,
						"subCategory": pin.SubCategory,
						"container":   pin.ContainerType,
						"linkedTo":    links,
					})
				}
				item["pins"] = pins
			case "Warnings":
				warnings := make([]string, 0, len(node.PropertiesWarnings)+len(node.PinParseWarnings))
				warnings = append(warnings, node.PropertiesWarnings...)
				warnings = append(warnings, node.PinParseWarnings...)
				item["warnings"] = warnings
			}
		}
		matches = append(matches, item)
		if *limit > 0 && len(matches) >= *limit {
			break
		}
	}

	return printJSON(stdout, map[string]any{
		"file":         file,
		"classFilter":  classToken,
		"memberFilter": memberToken,
		"nameFilter":   nameToken,
		"show":         showFields,
		"limit":        *limit,
		"matchCount":   len(matches),
		"matches":      matches,
		"warnings":     graph.Warnings,
	})
}

func parseBlueprintShowFields(raw string) ([]string, error) {
	tokens := strings.Split(raw, ",")
	seen := map[string]bool{}
	out := make([]string, 0, len(tokens))
	for _, token := range tokens {
		norm := strings.ToLower(strings.TrimSpace(token))
		if norm == "" {
			continue
		}
		var canonical string
		switch norm {
		case "nodepos", "node_pos":
			canonical = "NodePos"
		case "function", "member":
			canonical = "Function"
		case "pindefaults", "pin_defaults":
			canonical = "PinDefaults"
		case "pins":
			canonical = "Pins"
		case "warnings":
			canonical = "Warnings"
		default:
			return nil, fmt.Errorf("unsupported --show field: %s", token)
		}
		if !seen[canonical] {
			seen[canonical] = true
			out = append(out, canonical)
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("--show must include at least one field")
	}
	return out, nil
}

func splitNodePinToken(raw string) (string, string) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", ""
	}
	idx := strings.LastIndex(raw, ".")
	if idx <= 0 || idx >= len(raw)-1 {
		return raw, ""
	}
	return strings.TrimSpace(raw[:idx]), strings.TrimSpace(raw[idx+1:])
}

func buildBlueprintGraphIndex(asset *uasset.Asset) blueprintGraphIndex {
	graph := blueprintGraphIndex{
		Nodes:        make([]blueprintGraphNode, 0, 64),
		Edges:        make([]blueprintExecutionEdge, 0, 128),
		Warnings:     make([]string, 0, 16),
		nodeByExport: map[int]int{},
	}
	if asset == nil {
		graph.Warnings = append(graph.Warnings, "asset is nil")
		return graph
	}

	cfg := buildBlueprintGraphParseConfig(asset)
	hasOptimizedPins := hasCustomVersionAtLeast(asset, blueprintsObjectVersionGUID, blueprintVerEdGraphOptimized, true)

	for exportZeroIndex, exp := range asset.Exports {
		className := asset.ResolveClassName(exp)
		if !isBlueprintGraphNodeClass(className) {
			continue
		}

		node := blueprintGraphNode{
			ExportIndex:        exportZeroIndex + 1,
			ObjectName:         exp.ObjectName.Display(asset.Names),
			ClassName:          className,
			OuterIndex:         int32(exp.OuterIndex),
			PropertiesWarnings: make([]string, 0, 4),
			PinParseWarnings:   make([]string, 0, 4),
			decodedProperties:  map[string]any{},
		}
		node.GraphPath = resolveBlueprintOuterPath(asset, exp.OuterIndex)
		node.GraphName = firstGraphNameFromPath(node.GraphPath)

		props := asset.ParseExportProperties(exportZeroIndex)
		node.PropertiesWarnings = append(node.PropertiesWarnings, props.Warnings...)
		for _, p := range props.Properties {
			name := p.Name.Display(asset.Names)
			if v, ok := asset.DecodePropertyValue(p); ok {
				enrichDecodedTextValue(v)
				node.decodedProperties[name] = v
			}
		}
		readBlueprintNodeMetadata(&node)

		if hasOptimizedPins {
			pins := parseBlueprintNodePins(asset, exportZeroIndex, props.EndOffset, cfg)
			node.Pins = pins.Pins
			node.PinParseWarnings = append(node.PinParseWarnings, pins.Warnings...)
			node.PinParseStartOffset = pins.Start
			node.PinParseConsumedBytes = pins.Consumed
			node.pinParseConfig = pins.ConfigUsed
		} else {
			node.PinParseWarnings = append(node.PinParseWarnings, "pin parsing skipped: package custom version predates EdGraphPinOptimized")
		}

		graph.nodeByExport[node.ExportIndex] = len(graph.Nodes)
		graph.Nodes = append(graph.Nodes, node)
	}

	resolveBlueprintGraphLinks(&graph)
	buildBlueprintExecutionEdges(&graph)
	for _, node := range graph.Nodes {
		for _, warning := range node.PinParseWarnings {
			graph.Warnings = append(graph.Warnings, fmt.Sprintf("export %d (%s): %s", node.ExportIndex, node.ObjectName, warning))
		}
	}

	sort.Slice(graph.Nodes, func(i, j int) bool { return graph.Nodes[i].ExportIndex < graph.Nodes[j].ExportIndex })
	graph.nodeByExport = map[int]int{}
	for i := range graph.Nodes {
		graph.nodeByExport[graph.Nodes[i].ExportIndex] = i
	}
	sort.Slice(graph.Edges, func(i, j int) bool {
		a := graph.Edges[i]
		b := graph.Edges[j]
		if a.FromExportIndex != b.FromExportIndex {
			return a.FromExportIndex < b.FromExportIndex
		}
		if a.FromPin != b.FromPin {
			return a.FromPin < b.FromPin
		}
		if a.ToExportIndex != b.ToExportIndex {
			return a.ToExportIndex < b.ToExportIndex
		}
		return a.ToPin < b.ToPin
	})

	return graph
}

func (g blueprintGraphIndex) nodeForExport(exportIndex int) *blueprintGraphNode {
	if idx, ok := g.nodeByExport[exportIndex]; ok {
		return &g.Nodes[idx]
	}
	return nil
}

func traceBlueprintExecutionPath(
	graph blueprintGraphIndex,
	startExports []int,
	startPinToken string,
	targetFn func(blueprintGraphNode) bool,
	maxDepth int,
) ([]blueprintExecutionEdge, int, bool) {
	if maxDepth <= 0 || len(graph.Nodes) == 0 || len(startExports) == 0 {
		return nil, 0, false
	}
	adj := map[int][]blueprintExecutionEdge{}
	for _, edge := range graph.Edges {
		adj[edge.FromExportIndex] = append(adj[edge.FromExportIndex], edge)
	}

	type state struct {
		Export int
		Path   []blueprintExecutionEdge
	}
	queue := make([]state, 0, len(startExports))
	visitedDepth := map[int]int{}
	for _, exportIndex := range startExports {
		queue = append(queue, state{Export: exportIndex, Path: nil})
		visitedDepth[exportIndex] = 0
	}

	for len(queue) > 0 {
		current := queue[0]
		queue = queue[1:]
		node := graph.nodeForExport(current.Export)
		if node != nil && targetFn(*node) {
			return current.Path, current.Export, true
		}
		if len(current.Path) >= maxDepth {
			continue
		}
		for _, edge := range adj[current.Export] {
			if len(current.Path) == 0 && startPinToken != "" && !strings.EqualFold(edge.FromPin, startPinToken) {
				continue
			}
			nextDepth := len(current.Path) + 1
			if prevDepth, ok := visitedDepth[edge.ToExportIndex]; ok && prevDepth <= nextDepth {
				continue
			}
			visitedDepth[edge.ToExportIndex] = nextDepth
			nextPath := make([]blueprintExecutionEdge, 0, len(current.Path)+1)
			nextPath = append(nextPath, current.Path...)
			nextPath = append(nextPath, edge)
			queue = append(queue, state{Export: edge.ToExportIndex, Path: nextPath})
		}
	}
	return nil, 0, false
}

func findBlueprintNodeExports(graph blueprintGraphIndex, token string) []int {
	token = strings.TrimSpace(token)
	if token == "" {
		return nil
	}
	// Prefer exact match first.
	exact := make([]int, 0, 4)
	for _, node := range graph.Nodes {
		if nodeMatchesTokenExact(node, token) {
			exact = append(exact, node.ExportIndex)
		}
	}
	if len(exact) > 0 {
		sort.Ints(exact)
		return exact
	}
	contains := make([]int, 0, 8)
	for _, node := range graph.Nodes {
		if nodeMatchesToken(node, token) {
			contains = append(contains, node.ExportIndex)
		}
	}
	sort.Ints(contains)
	return contains
}

func nodeMatchesTokenExact(node blueprintGraphNode, token string) bool {
	if strings.EqualFold(node.ObjectName, token) {
		return true
	}
	for _, alias := range nodeAliases(node) {
		if strings.EqualFold(alias, token) {
			return true
		}
	}
	return false
}

func nodeMatchesToken(node blueprintGraphNode, token string) bool {
	if containsFold(node.ObjectName, token) {
		return true
	}
	for _, alias := range nodeAliases(node) {
		if containsFold(alias, token) {
			return true
		}
	}
	return false
}

func nodeMatchesMember(node blueprintGraphNode, token string) bool {
	if token == "" {
		return true
	}
	for _, v := range []string{
		node.FunctionMemberName,
		node.EventMemberName,
		node.CustomFunctionName,
		node.EventSignatureName,
		node.DelegatePropertyName,
	} {
		if containsFold(v, token) {
			return true
		}
	}
	return false
}

func nodeAliases(node blueprintGraphNode) []string {
	out := make([]string, 0, 6)
	appendAlias := func(v string) {
		v = strings.TrimSpace(v)
		if v == "" {
			return
		}
		for _, existing := range out {
			if strings.EqualFold(existing, v) {
				return
			}
		}
		out = append(out, v)
	}
	appendAlias(node.FunctionMemberName)
	appendAlias(node.EventMemberName)
	appendAlias(node.CustomFunctionName)
	appendAlias(node.EventSignatureName)
	appendAlias(node.DelegatePropertyName)
	return out
}

func collectBlueprintEventExports(graph blueprintGraphIndex) []int {
	out := make([]int, 0, 8)
	for _, node := range graph.Nodes {
		lc := strings.ToLower(node.ClassName)
		if strings.Contains(lc, "k2node_event") || node.EventMemberName != "" || node.CustomFunctionName != "" {
			out = append(out, node.ExportIndex)
		}
	}
	sort.Ints(out)
	return out
}

func summarizeBlueprintPinDefault(pin blueprintNodePin) (string, string) {
	if strings.TrimSpace(pin.DefaultValue) != "" {
		return pin.DefaultValue, "DefaultValue"
	}
	if strings.TrimSpace(pin.DefaultTextValue) != "" {
		return pin.DefaultTextValue, "DefaultTextValue"
	}
	if strings.TrimSpace(pin.AutogeneratedDefault) != "" {
		return pin.AutogeneratedDefault, "AutogeneratedDefaultValue"
	}
	if strings.TrimSpace(pin.DefaultObjectResolved) != "" && pin.DefaultObjectResolved != "null" {
		return pin.DefaultObjectResolved, "DefaultObject"
	}
	return "", ""
}

func matchBlueprintSoftPathOnPin(pin blueprintNodePin, softPathToken string) (string, string, bool) {
	if containsFold(pin.DefaultValue, softPathToken) {
		return pin.DefaultValue, "DefaultValue", true
	}
	if containsFold(pin.DefaultTextValue, softPathToken) {
		return pin.DefaultTextValue, "DefaultTextValue", true
	}
	if containsFold(pin.AutogeneratedDefault, softPathToken) {
		return pin.AutogeneratedDefault, "AutogeneratedDefaultValue", true
	}
	if containsFold(pin.DefaultObjectResolved, softPathToken) {
		return pin.DefaultObjectResolved, "DefaultObject", true
	}
	return "", "", false
}

func resolveBlueprintOuterPath(asset *uasset.Asset, outerIndex uasset.PackageIndex) []string {
	out := make([]string, 0, 4)
	current := outerIndex
	guard := 0
	for current > 0 && guard < 64 {
		idx := current.ResolveIndex()
		if idx < 0 || idx >= len(asset.Exports) {
			break
		}
		exp := asset.Exports[idx]
		out = append(out, exp.ObjectName.Display(asset.Names))
		current = exp.OuterIndex
		guard++
	}
	for i, j := 0, len(out)-1; i < j; i, j = i+1, j-1 {
		out[i], out[j] = out[j], out[i]
	}
	return out
}

func firstGraphNameFromPath(path []string) string {
	if len(path) == 0 {
		return ""
	}
	return path[len(path)-1]
}

func isBlueprintGraphNodeClass(className string) bool {
	lc := strings.ToLower(className)
	return strings.Contains(lc, "k2node") || strings.Contains(lc, "edgraphnode")
}

func buildBlueprintGraphParseConfig(asset *uasset.Asset) blueprintGraphParseConfig {
	cfg := blueprintGraphParseConfig{}
	cfg.PinsStoreFName = hasCustomVersionAtLeast(asset, frameworkObjectVersionGUID, frameworkVerPinsStoreFName, true)
	cfg.HasPinContainerType = hasCustomVersionAtLeast(asset, frameworkObjectVersionGUID, frameworkVerPinContainerType, true)
	cfg.HasPinFriendlyName = !asset.Summary.IsEditorOnlyFiltered()
	cfg.HasSourceIndex = hasCustomVersionAtLeast(asset, ue5MainObjectVersionGUID, ue5MainVerPinSourceIndex, true)
	cfg.HasPinUObjectWrapper = hasCustomVersionAtLeast(asset, releaseObjectVersionGUID, releaseVerPinUObjectWrapper, true)
	cfg.HasPinSerializeAsSinglePrecise = hasCustomVersionAtLeast(asset, ue5ReleaseObjectVersionGUID, ue5ReleaseVerPinFloatSingle, true)
	return cfg
}

func customVersion(asset *uasset.Asset, guid string) (int32, bool) {
	if asset == nil {
		return 0, false
	}
	for _, cv := range asset.Summary.CustomVersions {
		if strings.EqualFold(cv.Key.String(), guid) {
			return cv.Version, true
		}
	}
	return 0, false
}

func hasCustomVersionAtLeast(asset *uasset.Asset, guid string, min int32, defaultWhenMissing bool) bool {
	v, ok := customVersion(asset, guid)
	if !ok {
		return defaultWhenMissing
	}
	return v >= min
}

func readBlueprintNodeMetadata(node *blueprintGraphNode) {
	if node == nil {
		return
	}
	node.NodePosX, node.NodePosFound = extractIntLike(node.decodedProperties["NodePosX"])
	if y, ok := extractIntLike(node.decodedProperties["NodePosY"]); ok {
		node.NodePosY = y
		node.NodePosFound = node.NodePosFound || ok
	}
	node.NodeGUID = extractGuidString(node.decodedProperties["NodeGuid"])
	node.FunctionMemberName, node.FunctionMemberParent = extractMemberReference(node.decodedProperties["FunctionReference"])
	if node.FunctionMemberName == "" {
		node.FunctionMemberName, node.FunctionMemberParent = extractMemberReference(node.decodedProperties["MemberReference"])
	}
	node.EventMemberName, node.EventMemberParent = extractMemberReference(node.decodedProperties["EventReference"])
	node.CustomFunctionName = extractNameLikeValue(node.decodedProperties["CustomFunctionName"])
	node.EventSignatureName = extractNameLikeValue(node.decodedProperties["EventSignatureName"])
	node.DelegatePropertyName = extractNameLikeValue(node.decodedProperties["DelegatePropertyName"])
}

func extractMemberReference(raw any) (string, string) {
	root, ok := raw.(map[string]any)
	if !ok {
		return "", ""
	}
	payload, _ := root["value"].(map[string]any)
	if payload == nil {
		return "", ""
	}
	memberName := extractNameLikeValue(payload["MemberName"])
	memberParent := ""
	if parentRaw, ok := payload["MemberParent"].(map[string]any); ok {
		if valueMap, ok := parentRaw["value"].(map[string]any); ok {
			if resolved, ok := valueMap["resolved"].(string); ok {
				memberParent = resolved
			}
		}
	}
	return memberName, memberParent
}

func extractNameLikeValue(raw any) string {
	if raw == nil {
		return ""
	}
	if s, ok := raw.(string); ok {
		return s
	}
	root, ok := raw.(map[string]any)
	if !ok {
		return ""
	}
	if value, ok := root["value"]; ok {
		switch t := value.(type) {
		case string:
			return t
		case map[string]any:
			if name, ok := t["name"].(string); ok {
				return name
			}
			if v, ok := t["value"]; ok {
				if innerMap, ok := v.(map[string]any); ok {
					if name, ok := innerMap["name"].(string); ok {
						return name
					}
				}
			}
		}
	}
	if name, ok := root["name"].(string); ok {
		return name
	}
	return ""
}

func extractGuidString(raw any) string {
	if raw == nil {
		return ""
	}
	root, ok := raw.(map[string]any)
	if !ok {
		return ""
	}
	value, _ := root["value"].(string)
	return value
}

func extractIntLike(raw any) (int, bool) {
	switch v := raw.(type) {
	case int:
		return v, true
	case int8:
		return int(v), true
	case int16:
		return int(v), true
	case int32:
		return int(v), true
	case int64:
		return int(v), true
	case float32:
		return int(v), true
	case float64:
		return int(v), true
	case uint8:
		return int(v), true
	case uint16:
		return int(v), true
	case uint32:
		return int(v), true
	case uint64:
		return int(v), true
	default:
		return 0, false
	}
}

func asIntFromAny(v any) int {
	i, _ := extractIntLike(v)
	return i
}

func parseBlueprintNodePins(asset *uasset.Asset, exportZeroIndex int, propsEndOffset int, baseCfg blueprintGraphParseConfig) blueprintNodePinsParseResult {
	exp := asset.Exports[exportZeroIndex]
	serialStart := int(exp.SerialOffset)
	serialEnd := int(exp.SerialOffset + exp.SerialSize)
	if serialStart < 0 || serialEnd < serialStart || serialEnd > len(asset.Raw.Bytes) {
		return blueprintNodePinsParseResult{Warnings: []string{"export serial range out of bounds"}}
	}
	if propsEndOffset < serialStart || propsEndOffset > serialEnd {
		return blueprintNodePinsParseResult{Warnings: []string{"property end offset is outside export serial range"}}
	}

	starts := []int{propsEndOffset}
	if propsEndOffset+4 <= serialEnd {
		starts = append(starts, propsEndOffset+4)
	}
	cfgs := enumerateBlueprintParseConfigs(baseCfg)

	best := blueprintNodePinsParseResult{}
	bestScore := -1 << 30
	failureCount := 0
	firstFailure := ""
	for _, start := range starts {
		for _, cfg := range cfgs {
			candidate, err := parseBlueprintOwningNodePinArray(asset, serialEnd, start, cfg)
			if err != nil {
				failureCount++
				if firstFailure == "" {
					firstFailure = fmt.Sprintf("pin parse candidate rejected (start=%d cfg=%s): %v", start, formatBlueprintParseConfig(cfg), err)
				}
				continue
			}
			score := scoreBlueprintPinParse(candidate)
			if score > bestScore {
				bestScore = score
				best = candidate
			}
		}
	}
	if bestScore <= -1<<29 {
		warnings := make([]string, 0, 2)
		if firstFailure != "" {
			warnings = append(warnings, firstFailure)
		} else {
			warnings = append(warnings, "failed to parse pin array from any candidate")
		}
		if failureCount > 1 {
			warnings = append(warnings, fmt.Sprintf("%d additional pin parse candidates failed", failureCount-1))
		}
		return blueprintNodePinsParseResult{Warnings: warnings}
	}
	if best.Remaining > 4 {
		best.Warnings = append(best.Warnings, fmt.Sprintf("pin payload parsed with %d trailing bytes", best.Remaining))
	}
	if disabledParseFeatures(best.ConfigUsed) > disabledParseFeatures(baseCfg) {
		best.Warnings = append(best.Warnings, fmt.Sprintf("pin parse required relaxed layout assumptions (%s)", formatBlueprintParseConfig(best.ConfigUsed)))
	}
	return best
}

func enumerateBlueprintParseConfigs(base blueprintGraphParseConfig) []blueprintGraphParseConfig {
	toggles := make([]func(*blueprintGraphParseConfig), 0, 6)
	if base.HasPinFriendlyName {
		toggles = append(toggles, func(cfg *blueprintGraphParseConfig) { cfg.HasPinFriendlyName = false })
	}
	if base.HasSourceIndex {
		toggles = append(toggles, func(cfg *blueprintGraphParseConfig) { cfg.HasSourceIndex = false })
	}
	if base.HasPinUObjectWrapper {
		toggles = append(toggles, func(cfg *blueprintGraphParseConfig) { cfg.HasPinUObjectWrapper = false })
	}
	if base.HasPinSerializeAsSinglePrecise {
		toggles = append(toggles, func(cfg *blueprintGraphParseConfig) { cfg.HasPinSerializeAsSinglePrecise = false })
	}
	if base.HasPinContainerType {
		toggles = append(toggles, func(cfg *blueprintGraphParseConfig) { cfg.HasPinContainerType = false })
	}

	cfgs := make([]blueprintGraphParseConfig, 0, 1<<len(toggles))
	seen := map[string]bool{}
	for mask := 0; mask < (1 << len(toggles)); mask++ {
		cfg := base
		for i, toggle := range toggles {
			if mask&(1<<i) != 0 {
				toggle(&cfg)
			}
		}
		key := formatBlueprintParseConfig(cfg)
		if seen[key] {
			continue
		}
		seen[key] = true
		cfgs = append(cfgs, cfg)
	}
	sort.Slice(cfgs, func(i, j int) bool {
		return disabledParseFeatures(cfgs[i]) < disabledParseFeatures(cfgs[j])
	})
	return cfgs
}

func formatBlueprintParseConfig(cfg blueprintGraphParseConfig) string {
	return fmt.Sprintf(
		"fName=%t friendly=%t srcIndex=%t container=%t uobjWrap=%t floatSingle=%t",
		cfg.PinsStoreFName,
		cfg.HasPinFriendlyName,
		cfg.HasSourceIndex,
		cfg.HasPinContainerType,
		cfg.HasPinUObjectWrapper,
		cfg.HasPinSerializeAsSinglePrecise,
	)
}

func disabledParseFeatures(cfg blueprintGraphParseConfig) int {
	disabled := 0
	if !cfg.HasPinFriendlyName {
		disabled++
	}
	if !cfg.HasSourceIndex {
		disabled++
	}
	if !cfg.HasPinContainerType {
		disabled++
	}
	if !cfg.HasPinUObjectWrapper {
		disabled++
	}
	if !cfg.HasPinSerializeAsSinglePrecise {
		disabled++
	}
	return disabled
}

func parseBlueprintOwningNodePinArray(
	asset *uasset.Asset,
	serialEnd int,
	start int,
	cfg blueprintGraphParseConfig,
) (blueprintNodePinsParseResult, error) {
	if start < 0 || start > serialEnd {
		return blueprintNodePinsParseResult{}, fmt.Errorf("start out of range")
	}
	if start == serialEnd {
		return blueprintNodePinsParseResult{}, fmt.Errorf("start points to end of serial data")
	}
	r := uasset.NewByteReaderWithByteSwapping(asset.Raw.Bytes[start:serialEnd], asset.Summary.UsesByteSwappedSerialization())
	count, err := r.ReadInt32()
	if err != nil {
		return blueprintNodePinsParseResult{}, fmt.Errorf("read pin count: %w", err)
	}
	if count < 0 || count > maxBlueprintGraphPins {
		return blueprintNodePinsParseResult{}, fmt.Errorf("invalid pin count: %d", count)
	}

	pins := make([]blueprintNodePin, 0, count)
	for i := int32(0); i < count; i++ {
		pin, err := parseBlueprintOwningNodePin(asset, r, cfg, int(i))
		if err != nil {
			return blueprintNodePinsParseResult{}, fmt.Errorf("pin[%d]: %w", i, err)
		}
		if pin.Name == "" && pin.PinGUID == "" && pin.OwningNodeIndex == 0 {
			continue
		}
		pins = append(pins, pin)
	}

	result := blueprintNodePinsParseResult{
		Pins:       pins,
		Start:      start,
		Consumed:   r.Offset(),
		Remaining:  r.Remaining(),
		Warnings:   nil,
		ConfigUsed: cfg,
	}
	return result, nil
}

func scoreBlueprintPinParse(candidate blueprintNodePinsParseResult) int {
	score := len(candidate.Pins) * 20
	if candidate.Consumed > 0 {
		score += 5
	}
	if candidate.Remaining == 0 {
		score += 30
	} else if candidate.Remaining <= 8 {
		score += 20
	} else {
		score -= candidate.Remaining / 2
	}
	score -= disabledParseFeatures(candidate.ConfigUsed) * 3
	return score
}

func parseBlueprintOwningNodePin(
	asset *uasset.Asset,
	r *uasset.ByteReader,
	cfg blueprintGraphParseConfig,
	index int,
) (blueprintNodePin, error) {
	pin := blueprintNodePin{Index: index, SourceIndex: -1}
	isNull, err := readSerializedBool(r)
	if err != nil {
		return pin, fmt.Errorf("read pin null flag: %w", err)
	}
	if isNull {
		return pin, nil
	}
	wrapperOwner, err := r.ReadInt32()
	if err != nil {
		return pin, fmt.Errorf("read wrapper owner: %w", err)
	}
	wrapperGUID, err := r.ReadGUID()
	if err != nil {
		return pin, fmt.Errorf("read wrapper guid: %w", err)
	}

	owner, err := r.ReadInt32()
	if err != nil {
		return pin, fmt.Errorf("read owning node: %w", err)
	}
	pinGUID, err := r.ReadGUID()
	if err != nil {
		return pin, fmt.Errorf("read pin guid: %w", err)
	}
	pin.OwningNodeIndex = owner
	pin.PinGUID = pinGUID.String()
	if wrapperOwner != owner {
		pin.ParseWarnings = append(pin.ParseWarnings, fmt.Sprintf("wrapper owner mismatch: wrapper=%d body=%d", wrapperOwner, owner))
	}
	if !strings.EqualFold(wrapperGUID.String(), pin.PinGUID) {
		pin.ParseWarnings = append(pin.ParseWarnings, fmt.Sprintf("wrapper guid mismatch: wrapper=%s body=%s", wrapperGUID.String(), pin.PinGUID))
	}

	name, err := readBlueprintSerializedName(asset, r, cfg.PinsStoreFName)
	if err != nil {
		return pin, fmt.Errorf("read pin name: %w", err)
	}
	pin.Name = name

	if cfg.HasPinFriendlyName {
		friendly, ok := decodeBlueprintSerializedTextDisplay(asset, r)
		if !ok {
			return pin, fmt.Errorf("read pin friendly name: decode failed")
		}
		pin.PinFriendlyName = friendly
	}

	if cfg.HasSourceIndex {
		sourceIndex, err := r.ReadInt32()
		if err != nil {
			return pin, fmt.Errorf("read source index: %w", err)
		}
		pin.SourceIndex = sourceIndex
	}

	toolTip, err := r.ReadFString()
	if err != nil {
		return pin, fmt.Errorf("read tooltip: %w", err)
	}
	pin.PinToolTip = toolTip

	direction, err := r.ReadUint8()
	if err != nil {
		return pin, fmt.Errorf("read direction: %w", err)
	}
	pin.Direction = int(direction)
	pin.DirectionName = blueprintPinDirectionName(direction)

	pinType, err := parseBlueprintPinType(asset, r, cfg)
	if err != nil {
		return pin, fmt.Errorf("read pin type: %w", err)
	}
	pin.Category = pinType.Category
	pin.SubCategory = pinType.SubCategory
	pin.ContainerType = pinType.ContainerType
	pin.SubCategoryObjectIndex = pinType.SubCategoryObjectIndex
	pin.SubCategoryObjectResolve = pinType.SubCategoryObjectResolved

	defaultValue, err := r.ReadFString()
	if err != nil {
		return pin, fmt.Errorf("read default value: %w", err)
	}
	pin.DefaultValue = defaultValue

	autoDefaultValue, err := r.ReadFString()
	if err != nil {
		return pin, fmt.Errorf("read auto default value: %w", err)
	}
	pin.AutogeneratedDefault = autoDefaultValue

	defaultObject, err := r.ReadInt32()
	if err != nil {
		return pin, fmt.Errorf("read default object: %w", err)
	}
	pin.DefaultObjectIndex = defaultObject
	pin.DefaultObjectResolved = asset.ParseIndex(uasset.PackageIndex(defaultObject))

	defaultText, ok := decodeBlueprintSerializedTextDisplay(asset, r)
	if !ok {
		return pin, fmt.Errorf("read default text: decode failed")
	}
	pin.DefaultTextValue = defaultText

	linkedTo, err := parseBlueprintPinRefArray(r, maxBlueprintPinRefs)
	if err != nil {
		return pin, fmt.Errorf("read linked-to pin refs: %w", err)
	}
	pin.LinkedToRefs = linkedTo

	subPins, err := parseBlueprintPinRefArray(r, maxBlueprintPinRefs)
	if err != nil {
		return pin, fmt.Errorf("read sub-pin refs: %w", err)
	}
	pin.SubPinsRefs = subPins

	parentRef, err := parseBlueprintOptionalPinRef(r)
	if err != nil {
		return pin, fmt.Errorf("read parent pin ref: %w", err)
	}
	pin.ParentPinRef = parentRef

	passThroughRef, err := parseBlueprintOptionalPinRef(r)
	if err != nil {
		return pin, fmt.Errorf("read pass-through pin ref: %w", err)
	}
	pin.ReferencePassThroughRef = passThroughRef

	if cfg.HasPinFriendlyName {
		persistentGUID, err := r.ReadGUID()
		if err != nil {
			return pin, fmt.Errorf("read persistent guid: %w", err)
		}
		pin.PersistentGUID = persistentGUID.String()
		bitField, err := r.ReadUint32()
		if err != nil {
			return pin, fmt.Errorf("read persistent bitfield: %w", err)
		}
		pin.PersistentFlags = bitField
	}

	return pin, nil
}

type blueprintParsedPinType struct {
	Category                  string
	SubCategory               string
	ContainerType             string
	SubCategoryObjectIndex    int32
	SubCategoryObjectResolved string
}

func parseBlueprintPinType(asset *uasset.Asset, r *uasset.ByteReader, cfg blueprintGraphParseConfig) (blueprintParsedPinType, error) {
	out := blueprintParsedPinType{}
	category, err := readBlueprintSerializedName(asset, r, cfg.PinsStoreFName)
	if err != nil {
		return out, fmt.Errorf("read category: %w", err)
	}
	subCategory, err := readBlueprintSerializedName(asset, r, cfg.PinsStoreFName)
	if err != nil {
		return out, fmt.Errorf("read sub-category: %w", err)
	}
	out.Category = category
	out.SubCategory = subCategory

	subObj, err := r.ReadInt32()
	if err != nil {
		return out, fmt.Errorf("read sub-category object: %w", err)
	}
	out.SubCategoryObjectIndex = subObj
	out.SubCategoryObjectResolved = asset.ParseIndex(uasset.PackageIndex(subObj))

	containerRaw := uint8(0)
	if cfg.HasPinContainerType {
		containerRaw, err = r.ReadUint8()
		if err != nil {
			return out, fmt.Errorf("read container type: %w", err)
		}
		if containerRaw == 3 {
			if err := parseBlueprintTerminalType(asset, r, cfg.PinsStoreFName, cfg.HasPinUObjectWrapper); err != nil {
				return out, fmt.Errorf("read terminal type: %w", err)
			}
		}
	} else {
		isMap, err := readSerializedBool(r)
		if err != nil {
			return out, fmt.Errorf("read legacy isMap: %w", err)
		}
		if isMap {
			containerRaw = 3
			if err := parseBlueprintTerminalType(asset, r, cfg.PinsStoreFName, cfg.HasPinUObjectWrapper); err != nil {
				return out, fmt.Errorf("read legacy terminal type: %w", err)
			}
		}
		isSet, err := readSerializedBool(r)
		if err != nil {
			return out, fmt.Errorf("read legacy isSet: %w", err)
		}
		isArray, err := readSerializedBool(r)
		if err != nil {
			return out, fmt.Errorf("read legacy isArray: %w", err)
		}
		if !isMap {
			switch {
			case isArray:
				containerRaw = 1
			case isSet:
				containerRaw = 2
			default:
				containerRaw = 0
			}
		}
	}
	out.ContainerType = blueprintContainerTypeName(containerRaw)

	if _, err := readSerializedBool(r); err != nil { // bIsReference
		return out, fmt.Errorf("read isReference: %w", err)
	}
	if _, err := readSerializedBool(r); err != nil { // bIsWeakPointer
		return out, fmt.Errorf("read isWeakPointer: %w", err)
	}
	if err := parseBlueprintMemberReference(asset, r, cfg.PinsStoreFName); err != nil {
		return out, fmt.Errorf("read member reference: %w", err)
	}
	if _, err := readSerializedBool(r); err != nil { // bIsConst
		return out, fmt.Errorf("read isConst: %w", err)
	}
	if cfg.HasPinUObjectWrapper {
		if _, err := readSerializedBool(r); err != nil {
			return out, fmt.Errorf("read isUObjectWrapper: %w", err)
		}
	}
	if cfg.HasPinSerializeAsSinglePrecise {
		if _, err := readSerializedBool(r); err != nil {
			return out, fmt.Errorf("read serializeAsSinglePrecision: %w", err)
		}
	}
	return out, nil
}

func parseBlueprintTerminalType(asset *uasset.Asset, r *uasset.ByteReader, useFName bool, hasUObjectWrapper bool) error {
	if _, err := readBlueprintSerializedName(asset, r, useFName); err != nil {
		return fmt.Errorf("read terminal category: %w", err)
	}
	if _, err := readBlueprintSerializedName(asset, r, useFName); err != nil {
		return fmt.Errorf("read terminal sub-category: %w", err)
	}
	if _, err := r.ReadInt32(); err != nil {
		return fmt.Errorf("read terminal sub-category object: %w", err)
	}
	if _, err := readSerializedBool(r); err != nil {
		return fmt.Errorf("read terminal isConst: %w", err)
	}
	if _, err := readSerializedBool(r); err != nil {
		return fmt.Errorf("read terminal isWeak: %w", err)
	}
	if hasUObjectWrapper {
		if _, err := readSerializedBool(r); err != nil {
			return fmt.Errorf("read terminal isUObjectWrapper: %w", err)
		}
	}
	return nil
}

func parseBlueprintMemberReference(asset *uasset.Asset, r *uasset.ByteReader, useFName bool) error {
	if _, err := r.ReadInt32(); err != nil { // MemberParent
		return err
	}
	if _, err := readBlueprintSerializedName(asset, r, useFName); err != nil { // MemberName
		return err
	}
	if _, err := r.ReadGUID(); err != nil { // MemberGuid
		return err
	}
	return nil
}

func readBlueprintSerializedName(asset *uasset.Asset, r *uasset.ByteReader, useFName bool) (string, error) {
	if !useFName {
		return r.ReadFString()
	}
	idx, err := r.ReadInt32()
	if err != nil {
		return "", err
	}
	number, err := r.ReadInt32()
	if err != nil {
		return "", err
	}
	return uasset.NameRef{Index: idx, Number: number}.Display(asset.Names), nil
}

func parseBlueprintPinRefArray(r *uasset.ByteReader, max int32) ([]blueprintPinReference, error) {
	count, err := r.ReadInt32()
	if err != nil {
		return nil, err
	}
	if count < 0 || count > max {
		return nil, fmt.Errorf("invalid pin-ref count: %d", count)
	}
	refs := make([]blueprintPinReference, 0, count)
	for i := int32(0); i < count; i++ {
		ref, err := parseBlueprintOptionalPinRef(r)
		if err != nil {
			return nil, fmt.Errorf("pin-ref[%d]: %w", i, err)
		}
		if ref != nil {
			refs = append(refs, *ref)
		}
	}
	return refs, nil
}

func parseBlueprintOptionalPinRef(r *uasset.ByteReader) (*blueprintPinReference, error) {
	isNull, err := readSerializedBool(r)
	if err != nil {
		return nil, err
	}
	if isNull {
		return nil, nil
	}
	owner, err := r.ReadInt32()
	if err != nil {
		return nil, err
	}
	guid, err := r.ReadGUID()
	if err != nil {
		return nil, err
	}
	ref := &blueprintPinReference{OwningNodeIndex: owner, PinGUID: guid.String()}
	return ref, nil
}

func readSerializedBool(r *uasset.ByteReader) (bool, error) {
	return r.ReadUBool()
}

func decodeBlueprintSerializedTextDisplay(asset *uasset.Asset, r *uasset.ByteReader) (string, bool) {
	start := r.Offset()
	decoded, ok := asset.DecodeSerializedTextFromReader(r)
	if !ok {
		_ = r.Seek(start)
		return "", false
	}
	textMap, ok := decoded.(map[string]any)
	if !ok {
		return "", true
	}
	if display := textDisplayFromDecodedHistory(textMap); display != "" {
		return display, true
	}
	if v, ok := textMap["cultureInvariantString"].(string); ok {
		return v, true
	}
	if v, ok := textMap["sourceString"].(string); ok {
		return v, true
	}
	if v, ok := textMap["value"].(string); ok {
		return v, true
	}
	return "", true
}

func resolveBlueprintGraphLinks(graph *blueprintGraphIndex) {
	if graph == nil {
		return
	}
	type location struct {
		nodeIndex int
		pinIndex  int
	}
	lookup := map[string]location{}
	for ni := range graph.Nodes {
		for pi := range graph.Nodes[ni].Pins {
			pin := graph.Nodes[ni].Pins[pi]
			if pin.PinGUID == "" {
				continue
			}
			key := blueprintPinLookupKey(pin.OwningNodeIndex, pin.PinGUID)
			lookup[key] = location{nodeIndex: ni, pinIndex: pi}
		}
	}

	for ni := range graph.Nodes {
		for pi := range graph.Nodes[ni].Pins {
			pin := &graph.Nodes[ni].Pins[pi]
			resolved := make([]blueprintResolvedPinLink, 0, len(pin.LinkedToRefs))
			unresolved := make([]blueprintPinReference, 0)
			for _, ref := range pin.LinkedToRefs {
				loc, ok := lookup[blueprintPinLookupKey(ref.OwningNodeIndex, ref.PinGUID)]
				if !ok {
					unresolved = append(unresolved, ref)
					continue
				}
				node := graph.Nodes[loc.nodeIndex]
				targetPin := graph.Nodes[loc.nodeIndex].Pins[loc.pinIndex]
				resolved = append(resolved, blueprintResolvedPinLink{
					ExportIndex:   node.ExportIndex,
					NodeName:      node.ObjectName,
					NodeClassName: node.ClassName,
					PinName:       targetPin.Name,
					PinDirection:  targetPin.Direction,
					PinCategory:   targetPin.Category,
				})
			}
			sort.Slice(resolved, func(i, j int) bool {
				if resolved[i].ExportIndex != resolved[j].ExportIndex {
					return resolved[i].ExportIndex < resolved[j].ExportIndex
				}
				if resolved[i].NodeName != resolved[j].NodeName {
					return resolved[i].NodeName < resolved[j].NodeName
				}
				return resolved[i].PinName < resolved[j].PinName
			})
			pin.LinkedTo = resolved
			pin.UnresolvedLinkedTo = unresolved
		}
	}
}

func blueprintPinLookupKey(owningNodeIndex int32, guid string) string {
	return fmt.Sprintf("%d:%s", owningNodeIndex, strings.ToLower(strings.TrimSpace(guid)))
}

func buildBlueprintExecutionEdges(graph *blueprintGraphIndex) {
	if graph == nil {
		return
	}
	edges := make([]blueprintExecutionEdge, 0, 128)
	seen := map[string]bool{}
	for _, node := range graph.Nodes {
		for _, pin := range node.Pins {
			if !isBlueprintExecPin(pin) || pin.Direction != 1 {
				continue
			}
			for _, link := range pin.LinkedTo {
				if !strings.EqualFold(link.PinCategory, "exec") && link.PinCategory != "" {
					continue
				}
				if link.PinDirection != 0 {
					continue
				}
				edge := blueprintExecutionEdge{
					FromExportIndex: node.ExportIndex,
					FromNodeName:    node.ObjectName,
					FromPin:         pin.Name,
					ToExportIndex:   link.ExportIndex,
					ToNodeName:      link.NodeName,
					ToPin:           link.PinName,
				}
				key := fmt.Sprintf("%d:%s->%d:%s", edge.FromExportIndex, edge.FromPin, edge.ToExportIndex, edge.ToPin)
				if seen[key] {
					continue
				}
				seen[key] = true
				edges = append(edges, edge)
			}
		}
	}
	graph.Edges = edges
}

func isBlueprintExecPin(pin blueprintNodePin) bool {
	if strings.EqualFold(pin.Category, "exec") {
		return true
	}
	name := strings.ToLower(strings.TrimSpace(pin.Name))
	switch name {
	case "execute", "then", "completed", "pressed", "released", "inputkey", "outputdelegate":
		return true
	default:
		return false
	}
}

func blueprintPinDirectionName(raw uint8) string {
	switch raw {
	case 0:
		return "Input"
	case 1:
		return "Output"
	default:
		return fmt.Sprintf("Unknown(%d)", raw)
	}
}

func blueprintContainerTypeName(raw uint8) string {
	switch raw {
	case 0:
		return "None"
	case 1:
		return "Array"
	case 2:
		return "Set"
	case 3:
		return "Map"
	default:
		return fmt.Sprintf("Unknown(%d)", raw)
	}
}
